In [1]:
import twint
import pandas as pd
import numpy as np
import nest_asyncio
nest_asyncio.apply()

In [39]:
list = ["inflation_guy", "cnbc", "dylanmatt", "bloomberg", "wsj"]
for tweets in list:
    print(list)
    c = twint.Config()
    c.Search = "inflation"
    c.Hide_output = True
    c.Lang= "en"
    c.Pandas = True
    c.Since = "2016-01-01"
    c.near = "united_states"
    c.Limit = 1000
    twint.run.Search(c)
data = twint.output.panda.Tweets_df
data.head()

['inflation_guy', 'cnbc', 'dylanmatt', 'bloomberg', 'wsj']
['inflation_guy', 'cnbc', 'dylanmatt', 'bloomberg', 'wsj']
['inflation_guy', 'cnbc', 'dylanmatt', 'bloomberg', 'wsj']
['inflation_guy', 'cnbc', 'dylanmatt', 'bloomberg', 'wsj']
['inflation_guy', 'cnbc', 'dylanmatt', 'bloomberg', 'wsj']

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1442172170646458369,1442172170646458369,1.632676e+12,2021-09-26 13:00:14,-0400,,"Although the #NorthEast is up by 15% YoY, #pro...",en,"[northeast, property, prices]",[],...,,,,,,[],,,,
1,1442172129210888204,1442172129210888204,1.632676e+12,2021-09-26 13:00:04,-0400,,"26/09, Five cost of living crises facing the U...",en,[],[],...,,,,,,[],,,,
2,1442172122609160196,1442172122609160196,1.632676e+12,2021-09-26 13:00:02,-0400,,Our incomes destroyed by the world’s worst inf...,en,[lebanonprayer],[],...,,,,,,[],,,,
3,1442172118192381956,1442172118192381956,1.632676e+12,2021-09-26 13:00:01,-0400,,"This week if both so called ""Bills"" pass, you ...",en,[],[],...,,,,,,[],,,,
4,1442172117034881029,1442172117034881029,1.632676e+12,2021-09-26 13:00:01,-0400,,Don’t be fooled #inflation is not transitory! ...,en,"[inflation, goldcoretv, gold, silver, precious...",[],...,,,,,,[],,,,

In [41]:
Tweets_df

,date,tweet,hashtags,name,nlikes,nreplies,nretweets
0,2021-09-26 12:55:22,@FedResearch Very interesting discussion on in...,[],Fernando Colunga,0,0,0
1,2021-09-26 12:55:15,Inflation: Der fatale Irrglaube der EZB // Int...,[btc],Gabriel Kunzer 🟩,1,0,0
2,2021-09-26 12:55:00,"""Central banks often disregard food&amp;fuel i...",[],Michał,0,0,0
3,2021-09-26 12:54:59,what Americans seldom think about but feel is ...,[],les aaron friedlieb,0,0,0
4,2021-09-26 12:54:53,@Gator_NY I have 20 years in the industry. The...,[],Angelo,0,0,0
...,...,...,...,...,...,...,...
109,2021-09-26 12:38:52,@PeterRo18785637 @MarinaPurkiss Misleading tro...,[],knowgum #FBPA #NHSLove #FBPE #GTTO 3.5%,1,1,0
110,2021-09-26 12:38:51,@TorstenBell @theobertram @RachelReevesMP Labo...,[],Barry Dolan,0,0,0
111,2021-09-26 12:38:51,"@ScientixFinance If there are 50,000 scix toke...",[],Aelox.com,0,0,0
112,2021-09-26 12:38:51,"1) Vote for BJP : - Means Corruption, Rise i...",[],Sourcasm,6,0,2
113,2021-09-26 12:38:42,Company defaults in China aren’t a potential c...,[],Raymond lee veazey,0,0,0

In [42]:
Tweets_df = twint.storage.panda.Tweets_df

In [43]:
Tweets_df

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1442172170646458369,1442172170646458369,1.632676e+12,2021-09-26 13:00:14,-0400,,"Although the #NorthEast is up by 15% YoY, #pro...",en,"[northeast, property, prices]",[],...,,,,,,[],,,,
1,1442172129210888204,1442172129210888204,1.632676e+12,2021-09-26 13:00:04,-0400,,"26/09, Five cost of living crises facing the U...",en,[],[],...,,,,,,[],,,,
2,1442172122609160196,1442172122609160196,1.632676e+12,2021-09-26 13:00:02,-0400,,Our incomes destroyed by the world’s worst inf...,en,[lebanonprayer],[],...,,,,,,[],,,,
3,1442172118192381956,1442172118192381956,1.632676e+12,2021-09-26 13:00:01,-0400,,"This week if both so called ""Bills"" pass, you ...",en,[],[],...,,,,,,[],,,,
4,1442172117034881029,1442172117034881029,1.632676e+12,2021-09-26 13:00:01,-0400,,Don’t be fooled #inflation is not transitory! ...,en,"[inflation, goldcoretv, gold, silver, precious...",[],...,,,,,,[],,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010,1442137737386074113,1442128367285727242,1.632667e+12,2021-09-26 10:43:24,-0400,,@gmangeegee @TomCottonAR @KellyannePolls Great...,en,[],[],...,,,,,,"[{'screen_name': 'gmangeegee', 'name': 'Graeme...",,,,
1011,1442137721850499074,1442130184761593861,1.632667e+12,2021-09-26 10:43:21,-0400,,"@EJDionne The focus on the top line number, wi...",en,[],[],...,,,,,,"[{'screen_name': 'EJDionne', 'name': 'EJ Dionn...",,,,
1012,1442137677474631688,1441819746127724545,1.632667e+12,2021-09-26 10:43:10,-0400,,@ChristianM_28 @AndrewYang You think UBI will ...,en,[],[],...,,,,,,"[{'screen_name': 'ChristianM_28', 'name': 'Chr...",,,,
1013,1442137654296858632,1442137654296858632,1.632667e+12,2021-09-26 10:43:05,-0400,,Reminder: You can’t be bullish energy without ...,en,[],[],...,,,,,,[],,,,
1014,1442137632880807936,1442137632880807936,1.632667e+12,2021-09-26 10:42:59,-0400,,A hamster has been #trading #cryptocurrencies ...,en,"[trading, cryptocurrencies, tokens, bitcoin, b...",[spy],...,,,,,,[],,,,

In [44]:
Tweets_df['hashtags']

0                           [northeast, property, prices]
1                                                      []
2                                         [lebanonprayer]
3                                                      []
4       [inflation, goldcoretv, gold, silver, precious...
                              ...
1010                                                   []
1011                                                   []
1012                                                   []
1013                                                   []
1014    [trading, cryptocurrencies, tokens, bitcoin, b...
Name: hashtags, Length: 1015, dtype: object

In [45]:
Tweets_df.drop(['id', 'conversation_id', 'created_at', 'timezone', 'place', 'language','cashtags', 'user_id', 'user_id_str','username', 'day', 'hour', 'link', 'urls', 'photos', 'video', 'thumbnail', 'retweet', 'quote_url', 'search', 'near', 'geo', 'source', 'user_rt_id', 'user_rt',
       'retweet_id', 'reply_to', 'retweet_date', 'translate', 'trans_src',
       'trans_dest'], axis = 1, inplace = True)

In [46]:
Tweets_df

,date,tweet,hashtags,name,nlikes,nreplies,nretweets
0,2021-09-26 13:00:14,"Although the #NorthEast is up by 15% YoY, #pro...","[northeast, property, prices]",katefaulkner,0,0,0
1,2021-09-26 13:00:04,"26/09, Five cost of living crises facing the U...",[],Daily Tory,0,0,0
2,2021-09-26 13:00:02,Our incomes destroyed by the world’s worst inf...,[lebanonprayer],Jayson Casper,0,0,0
3,2021-09-26 13:00:01,"This week if both so called ""Bills"" pass, you ...",[],D. Craig,1,0,0
4,2021-09-26 13:00:01,Don’t be fooled #inflation is not transitory! ...,"[inflation, goldcoretv, gold, silver, precious...",GoldCore,0,0,0
...,...,...,...,...,...,...,...
1010,2021-09-26 10:43:24,@gmangeegee @TomCottonAR @KellyannePolls Great...,[],Sorry Charlie,0,1,0
1011,2021-09-26 10:43:21,"@EJDionne The focus on the top line number, wi...",[],ContraFictional,0,0,0
1012,2021-09-26 10:43:10,@ChristianM_28 @AndrewYang You think UBI will ...,[],selekedi mafate,0,1,0
1013,2021-09-26 10:43:05,Reminder: You can’t be bullish energy without ...,[],Christian Klein,10,2,2
1014,2021-09-26 10:42:59,A hamster has been #trading #cryptocurrencies ...,"[trading, cryptocurrencies, tokens, bitcoin, b...",Zakaria Bziker,1,0,0